name: rctl
base: core18
version: git
summary: A command line tool for Routr Server
description: rctl is a command line tool for Routr Servers using the API.
license: MIT
assumes: [snapd2.42]
grade: stable
confinement: devmode

parts:
  rctl:
    plugin: nodejs
    source: .
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - openjdk-8-jre-headless

plugs:
  rctl-config:
    interface: personal-files
    write:
      - $HOME/.routr-access.json

apps:
  rctl:
    command: rctl
    plugs:
      - home
      - network
      - rctl-config
